# Site settings
title: IE LAB
email: ws_choi@korea.ac.kr
address: Lyceum 321B, KOREA UNIVERSITY, Anam-ro 145, Seongbuk-gu, Seoul, Korea
phone: +82 010-0000-0000 # TODO 번호 수정 필요
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

paginate: 10
paginate_path: "news/page:num"
